"""stage 1-3: recipe versions, supplier fk, inventory batches, waste logs, price history, order line items, kitchen tasks, temperature logs, shift notes

Revision ID: 8eebf19b2106
Revises: 210c4a92a77a
Create Date: 2026-07-17 11:31:57.807514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eebf19b2106'
down_revision = '210c4a92a77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('recurring', sa.String(length=20), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_kitchen_tasks_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kitchen_tasks'))
    )
    with op.batch_alter_table('kitchen_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kitchen_tasks_org_id'), ['org_id'], unique=False)

    op.create_table('temperature_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('reading_type', sa.String(length=20), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_temperature_logs_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temperature_logs'))
    )
    with op.batch_alter_table('temperature_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temperature_logs_org_id'), ['org_id'], unique=False)

    op.create_table('recipe_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_recipe_versions_org_id_organizations')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_versions_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_versions'))
    )
    with op.batch_alter_table('recipe_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_versions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_versions_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('shift_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_shift_notes_author_id_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_shift_notes_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_notes'))
    )
    with op.batch_alter_table('shift_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_notes_org_id'), ['org_id'], unique=False)

    op.create_table('inventory_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('expires', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_inventory_batches_inventory_item_id_inventory_items')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_inventory_batches_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_batches'))
    )
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_batches_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_org_id'), ['org_id'], unique=False)

    op.create_table('order_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('qty_ordered', sa.Float(), nullable=True),
    sa.Column('qty_received', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_order_line_items_inventory_item_id_inventory_items')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_line_items_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_line_items'))
    )
    with op.batch_alter_table('order_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_line_items_order_id'), ['order_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_price_history_inventory_item_id_inventory_items')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_price_history_org_id_organizations')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_price_history_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history'))
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_org_id'), ['org_id'], unique=False)

    op.create_table('waste_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=20), nullable=True),
    sa.Column('cost_impact', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_waste_logs_inventory_item_id_inventory_items')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_waste_logs_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_logs'))
    )
    with op.batch_alter_table('waste_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waste_logs_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waste_logs_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_items_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_inventory_items_supplier_id_suppliers'), 'suppliers', ['supplier_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invoice_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('received_at', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_orders_supplier_id_suppliers'), 'suppliers', ['supplier_id'], ['id'])

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('storage_notes', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('shelf_life_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('shelf_life_days')
        batch_op.drop_column('storage_notes')
        batch_op.drop_column('menu_price')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_supplier_id_suppliers'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_supplier_id'))
        batch_op.drop_column('received_at')
        batch_op.drop_column('invoice_url')
        batch_op.drop_column('supplier_id')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_items_supplier_id_suppliers'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_items_supplier_id'))
        batch_op.drop_column('supplier_id')

    with op.batch_alter_table('waste_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waste_logs_org_id'))
        batch_op.drop_index(batch_op.f('ix_waste_logs_inventory_item_id'))

    op.drop_table('waste_logs')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_org_id'))
        batch_op.drop_index(batch_op.f('ix_price_history_inventory_item_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('order_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_line_items_order_id'))

    op.drop_table('order_line_items')
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_batches_org_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_inventory_item_id'))

    op.drop_table('inventory_batches')
    with op.batch_alter_table('shift_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_notes_org_id'))

    op.drop_table('shift_notes')
    with op.batch_alter_table('recipe_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_versions_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_versions_org_id'))

    op.drop_table('recipe_versions')
    with op.batch_alter_table('temperature_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temperature_logs_org_id'))

    op.drop_table('temperature_logs')
    with op.batch_alter_table('kitchen_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kitchen_tasks_org_id'))

    op.drop_table('kitchen_tasks')
    # ### end Alembic commands ###
