"""v2: ingredient database, recipe nutrition auto-calc, user position field

Revision ID: c5f7de61b88f
Revises: 8eebf19b2106
Create Date: 2026-07-20 22:50:08.801951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f7de61b88f'
down_revision = '8eebf19b2106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('default_unit', sa.String(length=20), nullable=True),
    sa.Column('grams_per_unit', sa.JSON(), nullable=True),
    sa.Column('kcal_per100g', sa.Float(), nullable=True),
    sa.Column('protein_per100g', sa.Float(), nullable=True),
    sa.Column('carbs_per100g', sa.Float(), nullable=True),
    sa.Column('fat_per100g', sa.Float(), nullable=True),
    sa.Column('allergens', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_ingredients_org_id_organizations')),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_ingredients_verified_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredients_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrition_source', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('nutrition_source')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_org_id'))

    op.drop_table('ingredients')
    # ### end Alembic commands ###
